// <auto-generated />
namespace GTSharp.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Package1GTS003 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Package1GTS003));
        
        string IMigrationMetadata.Id
        {
            get { return "201909081901534_Package1GTS003"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
